package view;

import constants.FileLocation;
import helper.CheckFile;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author: Pedro Afonso Ferreira Haupenthal
 * Email: pedro.haupenthal@gmail.com
 */
public class MainForm extends javax.swing.JFrame {

    public MainForm() {
        initComponents();
        ConfigForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rbBranco = new javax.swing.JRadioButton();
        rbVermelho = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAcidezFixada = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAcidezVolatil = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAcidezCitrica = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAcucar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCloretos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDioEnxofreLivre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDioEnxofreTotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDensidade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPh = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtSulfatos = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtAlcool = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();
        btnIniciar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        lblTipoVinho = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        lblQualidadeVinho = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Wine Analitycs");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Entrada", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tipo de vinho a ser analisado:");

        rbBranco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbBranco.setText("Branco");

        rbVermelho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbVermelho.setText("Vermelho");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Propriedades do vinho:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Acidez fixada:");

        txtAcidezFixada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAcidezFixadaKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Acidez volátil:");

        txtAcidezVolatil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAcidezVolatilKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Acidez cítrica:");

        txtAcidezCitrica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAcidezCitricaKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Acúcar residual:");

        txtAcucar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAcucarKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Cloretos:");

        txtCloretos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCloretosKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Dióxido enxofre livre:");

        txtDioEnxofreLivre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDioEnxofreLivreKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Dióxido enxofre total:");

        txtDioEnxofreTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDioEnxofreTotalKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Densidade:");

        txtDensidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDensidadeKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("pH:");

        txtPh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Sulfatos:");

        txtSulfatos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSulfatosKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Alcool:");

        txtAlcool.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAlcoolKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbBranco)
                        .addGap(18, 18, 18)
                        .addComponent(rbVermelho))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAcidezVolatil, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAcidezFixada)
                            .addComponent(txtAcidezCitrica, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCloretos, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAcucar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDioEnxofreLivre)
                            .addComponent(txtAlcool)
                            .addComponent(txtSulfatos)
                            .addComponent(txtPh)
                            .addComponent(txtDensidade)
                            .addComponent(txtDioEnxofreTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbBranco)
                    .addComponent(rbVermelho))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAcidezFixada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAcidezVolatil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAcidezCitrica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAcucar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCloretos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDioEnxofreLivre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtDioEnxofreTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtDensidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtPh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtSulfatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtAlcool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Saída", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        lbl1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl1.setText("Status: ");
        lbl1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lbl1PropertyChange(evt);
            }
        });

        lblStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblStatus.setText("status");
        lblStatus.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblStatusPropertyChange(evt);
            }
        });

        btnIniciar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Clique no botão abaixo para analisar");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Resultados da análise:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Tipo de vinho:");

        lblTipoVinho.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTipoVinho.setText("tipo");

        btnLimpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Qualidade:");

        lblQualidadeVinho.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblQualidadeVinho.setText("qualidade");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbl1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblStatus))
                            .addComponent(jLabel15)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel16)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(lblTipoVinho))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(lblQualidadeVinho)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(lbl1))
                .addGap(18, 18, 18)
                .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lblTipoVinho))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(lblQualidadeVinho))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lbl1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl1PropertyChange

    private void lblStatusPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblStatusPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lblStatusPropertyChange

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        
        if(VerificarCampos()){
            try {
                GravarArqVinho();
            
                new CheckFile(lblStatus, ProgressBar, lblQualidadeVinho).start();
            
                if(rbBranco.isSelected()){
                    lblTipoVinho.setText("Branco");
             
                    Runtime.getRuntime().exec("cmd /c start "+FileLocation.EXEC+
                                        " /k \"cd "+FileLocation.LOCAL_ARCHIVE+
                                        " && "+FileLocation.ARCHIVE_NAME_WHITE+"\"");
                }
                else{
                    lblTipoVinho.setText("Vermelho");
                    Runtime.getRuntime().exec("cmd /c start "+FileLocation.EXEC+
                                        " /k \"cd "+FileLocation.LOCAL_ARCHIVE+
                                        " && "+FileLocation.ARCHIVE_NAME_RED+"\"");
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ocorreu um erro ao tentar analisar o vinho");
            }
        }
        
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        Clear();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtAcidezFixadaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAcidezFixadaKeyTyped
        MascaraNumeros(evt);
    }//GEN-LAST:event_txtAcidezFixadaKeyTyped

    private void txtAcidezVolatilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAcidezVolatilKeyTyped
        MascaraNumeros(evt);
    }//GEN-LAST:event_txtAcidezVolatilKeyTyped

    private void txtAcidezCitricaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAcidezCitricaKeyTyped
        MascaraNumeros(evt);
    }//GEN-LAST:event_txtAcidezCitricaKeyTyped

    private void txtAcucarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAcucarKeyTyped
        MascaraNumeros(evt);
    }//GEN-LAST:event_txtAcucarKeyTyped

    private void txtCloretosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCloretosKeyTyped
        MascaraNumeros(evt);
    }//GEN-LAST:event_txtCloretosKeyTyped

    private void txtDioEnxofreLivreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDioEnxofreLivreKeyTyped
        MascaraNumeros(evt);
    }//GEN-LAST:event_txtDioEnxofreLivreKeyTyped

    private void txtDioEnxofreTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDioEnxofreTotalKeyTyped
        MascaraNumeros(evt);
    }//GEN-LAST:event_txtDioEnxofreTotalKeyTyped

    private void txtDensidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDensidadeKeyTyped
        MascaraNumeros(evt);
    }//GEN-LAST:event_txtDensidadeKeyTyped

    private void txtPhKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhKeyTyped
        MascaraNumeros(evt);
    }//GEN-LAST:event_txtPhKeyTyped

    private void txtSulfatosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSulfatosKeyTyped
        MascaraNumeros(evt);
    }//GEN-LAST:event_txtSulfatosKeyTyped

    private void txtAlcoolKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlcoolKeyTyped
        MascaraNumeros(evt);
    }//GEN-LAST:event_txtAlcoolKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lblQualidadeVinho;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTipoVinho;
    private javax.swing.JRadioButton rbBranco;
    private javax.swing.JRadioButton rbVermelho;
    private javax.swing.JTextField txtAcidezCitrica;
    private javax.swing.JTextField txtAcidezFixada;
    private javax.swing.JTextField txtAcidezVolatil;
    private javax.swing.JTextField txtAcucar;
    private javax.swing.JTextField txtAlcool;
    private javax.swing.JTextField txtCloretos;
    private javax.swing.JTextField txtDensidade;
    private javax.swing.JTextField txtDioEnxofreLivre;
    private javax.swing.JTextField txtDioEnxofreTotal;
    private javax.swing.JTextField txtPh;
    private javax.swing.JTextField txtSulfatos;
    // End of variables declaration//GEN-END:variables
    public void ConfigForm(){
        this.setTitle("Wine Analytics");
        this.setResizable(false);
        
        ButtonGroup bg = new ButtonGroup();
        bg.add(rbBranco);
        bg.add(rbVermelho);
        rbVermelho.setSelected(true);
        
        Clear();
    }
    
    public void DeleteArchives(){
        File output;
        //wine
        output = new File(FileLocation.LOCAL_OUTPUTS+"\\"+FileLocation.OUTPUT_WINE);
        if(output.exists()){
            output.delete();
        }
        //quality
        output = new File(FileLocation.LOCAL_OUTPUTS+"\\"+FileLocation.OUTPUT_QLT);
        if(output.exists()){
            output.delete();
        }
    }
    
    public void Clear(){
        lblStatus.setText("Pronto");
        lblStatus.setForeground(Color.blue);
        ProgressBar.setIndeterminate(false);
        rbBranco.setSelected(true);
        lblTipoVinho.setText("não determinado");
        lblTipoVinho.setForeground(Color.black);
        lblQualidadeVinho.setText("não analisada");
        lblQualidadeVinho.setForeground(Color.black);
        txtAcidezCitrica.setText("");
        txtAcidezFixada.setText("");
        txtAcidezVolatil.setText("");
        txtDioEnxofreLivre.setText("");
        txtAcucar.setText("");
        txtAcucar.setText("");
        txtAlcool.setText("");
        txtCloretos.setText("");
        txtDensidade.setText("");
        txtDioEnxofreTotal.setText("");
        txtPh.setText("");
        txtSulfatos.setText("");
        DeleteArchives();
    }
    
    private void GravarArqVinho() throws IOException{
        
        FileWriter arq = new FileWriter(constants.FileLocation.LOCAL_OUTPUTS+"\\"+constants.FileLocation.OUTPUT_WINE);
        PrintWriter gravarArq = new PrintWriter(arq);

        gravarArq.printf("%s;%s;%s;%s;%s;%s;%s;%s;%s;%s;%s", txtAcidezFixada.getText(), txtAcidezVolatil.getText(), txtAcidezCitrica.getText(),
                                    txtAcucar.getText(), txtCloretos.getText(), txtDioEnxofreLivre.getText(),
                                    txtDioEnxofreTotal.getText(), txtDensidade.getText(), txtPh.getText(),
                                    txtSulfatos.getText(), txtAlcool.getText());

        arq.close();
    }
    
    private boolean VerificarCampos(){
        if(txtAcidezCitrica.getText().equals("") || txtAcidezFixada.getText().equals("") ||
            txtAcidezVolatil.getText().equals("") || txtDioEnxofreLivre.getText().equals("") ||
            txtAcucar.getText().equals("") || txtAcucar.getText().equals("") ||
            txtAlcool.getText().equals("") || txtCloretos.getText().equals("") ||
            txtDensidade.getText().equals("") || txtDioEnxofreTotal.getText().equals("") ||
            txtPh.getText().equals("") || txtSulfatos.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Todos as propriedades do vinho devem ser preenchidas.");
            return false;
        }
        else{
            return true;
        }
    }

    private void MascaraNumeros(KeyEvent evt) {
        String caracteres="0987654321.";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }
}
